services:
  - type: web
    name: portfolio-backend
    runtime: go
    plan: free
    rootDir: backend-go
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-postgres
          property: connectionString
      - key: GITHUB_TOKEN
        sync: false

databases:
  - name: portfolio-postgres
    plan: free

